### ISSUE TITLE
TypeError when using observable-hooks higher up in component tree

### ISSUE THREAD

**Issue by jkhaui** [crimx/observable-hooks#2] opened 2019-10-16 07:19 UTC
Great idea to combine RxJS with React hooks. An issue I have encountered is trying to create an observable higher up in my component tree. For example, consider the following code below:

```
  const keydown$ = fromEvent(document, 'keydown')
    .pipe(
      throttleTime(1500),
    );
  useSubscription(keydown$, (e: any) => {
    const { key } = e;
    if (key === 'PageUp' || key === 'PageDown') {
      e.preventDefault();
      e.stopPropagation();
      console.log(e);
    }
  });
```

Lets say my app structure looks something like Root -> AppContainer -> SomeComponent.
Putting the above code in the AppContainer component throws the following TypeError: `TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.`

However, putting the exact same code in SomeComponent works as expected. I believe this issue is related to the observable hook and not RxJS because if I just create the observable and console.log() it without the subscription, I can see it's getting created fine. Any ideas? Thanks!

**Comment by crimx** [comment] 2019-10-16 12:42
Hi, can you make an reproducible repo? `useSubscription` does nothing more than subscribe a stream. I don't see how it can cause the issue.

**Comment by jkhaui** [comment] 2019-10-18 02:39
Hey, yeah perhaps it's something to do with my code, I'll try and get a demo up on stackblitz. Thanks

**Comment by crimx** [comment] 2019-11-22 04:38
Looks like this has something to do with your operators. I'm closing this as it's not likely a bug of this library. Reopen if you need more discussion.

**Closed by crimx** 2019-11-22 04:38 UTC
